### ISSUE TITLE
Kernel recognition

### ISSUE THREAD

**Issue by BHaugGZPK** [trife/1KK#1]
- app struggles to identify all kernels on the background, **only about 30% are recognized, sometimes no kernel at all**
- tried with corn and wheat kernels
- tried several lightning schemes (different artificial indoor light sources, natural daylight direct/shadow)
- info: colors of background seemed all much darker than the very bright green on my screen

Requests: 
- options to set cutoff values for recognition parameters
- please more hints / tips in the manual on issues like described above (lightning, background colours...)

**Comment by trife** [comment]
Only kernels that are identified as being individual are used to extract morphological parameters. The next major update will resolve the background issues you're experiencing, partly by incorporating similar options as your requests.

**Comment by trife** [comment]
Please evaluate the new version which has an improved workflow, major technical updates, and new algorithm.
