### ISSUE TITLE
Sharpness images - no autofocus

### ISSUE THREAD

**Issue by BHaugGZPK** [trife/1KK#3]
I do not know if this is an issue, but just to inform you that the images i take are not at all sharp but more or less blurred. Autofocus does not seem to get activated.

**Comment by trife** [comment]
What device are you using? Autofocus and the camera API in general are notorious for being highly-dependent on the device manufacturer's implementation.

**Comment by BHaugGZPK** [comment]
I am using a Samsung Galaxy GT-I8262, Android 4.1.2. Autofocus works when taking the same images (green background with kernels, same lightning scheme etc.) with the native camera app.

**Comment by trife** [comment]
Fixed in v2
